language: go
go:
    - 1.2

language: ruby
rvm:
  - 1.9.3
  - 2.1.0

language: perl
perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
    - "5.8"
install: /bin/true
script: travis/all.sh
